### ISSUE TITLE
Swap etc

### ISSUE THREAD

**Issue by Kodiman** [stevleibelt/arch-linux-live-cd-iso-with-zfs#13]
Hi, Stev, Your fork of Arch-Config zfs script is excellent. Particularly the improvements you made. Please consider adding a feature to create encrypted swap partition. Your thoughts about this? Much appreciated. Thanks

See this link for information and syntax about swap. Perhaps can copy and paste this into your scripts...
https://wiki.archlinux.org/title/User:Kayvlim/Install_UEFI_and_BIOS_compatible_Arch_Linux_with_Encrypted_ZFS_and_ZFSBootMenu#Swap...
Please note sections 2.1.4, 2.2, 2.3.2, 2.3.3, and 4.2 regarding swap.

[The issues tab did not appear in your Arch-Config  repo so posted here.]

**Comment by stevleibelt** [comment]
@Kodiman thanks for your report. I've added the issue section and moved your issue to the [right repository](https://github.com/stevleibelt/arch-linux-configuration/issues/1).
