### ISSUE TITLE
modprobe btrfs: Key was rejected by service

### ISSUE THREAD

**Issue by thorstenhirsch** [stevleibelt/arch-linux-live-cd-iso-with-zfs#16]
Hi Stev, I'm looking for a live distribution that comes with both, BTRFS and ZFS. Since the official arch iso comes with BTRFS your iso seemed to be perfect, but unfortunately in the current release BTRFS is not working, /proc/filesystems does not contain it. So I tried to load the module:

```modprobe: ERROR: could not insert 'btrfs': Key was rejected by service```

I looked for "signature" in the `modinfo` output of some modules to find details about the key that has been used for signing the modules. But I couldn't find what's causing the problem, because the btrfs module is signed with the same key as all the other (loaded) modules - except for zfs, which is signed with a different key. But the zfs module also works fine. So I have no clue what's wrong with the btrfs module.

**Comment by stevleibelt** [comment]
Hey @thorstenhirsch I have absolutely no clue when it comes to btrfs.

Could you verify if your issue exists in the official archiso build to?

**Comment by stevleibelt** [comment]
@thorstenhirsch I've just build a new iso (which is available on [archzfs.leibelt.de](https://archzfs.leibelt.de/)) and was able to run it via `run_archiso`.

I was able to execute `btrfs` as command and got no error. But you are right, `/proc/filesystems | grep -q -i btrfs; echo ${?}` results in `1`.

**Comment by stevleibelt** [comment]
I've just downloaded [archlinux-2023.02.01-x86_64.iso](http://ftp.hosteurope.de/mirror/ftp.archlinux.org/iso/2023.02.01/archlinux-2023.02.01-x86_64.iso) and gave it a try and there is also no btrfs in `/proc/filesytems`.

**Comment by thorstenhirsch** [comment]
The `btrfs` command is not affected. The problem is specific to loading modules like `modprobe btrfs`. There are a lot of commands related to signing the kernel and initrd in arch's official iso build script (https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/archiso/mkarchiso)... I think we have to look there.

**Comment by thorstenhirsch** [comment]
> I've just downloaded [archlinux-2023.02.01-x86_64.iso](http://ftp.hosteurope.de/mirror/ftp.archlinux.org/iso/2023.02.01/archlinux-2023.02.01-x86_64.iso) and gave it a try and there is also no btrfs in `/proc/filesytems`.

But there I can successfully modprobe it.

**Comment by stevleibelt** [comment]
> The `btrfs` command is not affected. The problem is specific to loading modules like `modprobe btrfs`. There are a lot of commands related to signing the kernel and initrd in arch's official iso build script (https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/archiso/mkarchiso)... I think we have to look there.

Feel free to create a pull request. I simple have no time for that.

**Comment by thorstenhirsch** [comment]
Well, I'm still far away from finding the solution. But guess what - the official Ubuntu 22.04.1 iso has the same problem, just the other way round. There I can load btrfs successfully, but `modprobe zfs` gives me the `Key was rejected by service` error.  🤣

**Comment by stevleibelt** [comment]
So just for the log, the [archiso wikipage](https://wiki.archlinux.org/title/Archiso) does not contain anything about this issue. From the official forum, I just found [this](https://bbs.archlinux.org/viewtopic.php?id=282291) thread which is about signing UEFI-Bios.

That is pretty much al I found. Again and to be fully transparent here, I won't spend more time than now solving this issue.

I've assigned this issue to you. Feel free to create a pull request or write about your gained knowledge here. If you won't spend time on it, please close this ticket.

Cheers,
Stev

**Comment by stevleibelt** [comment]
@thorstenhirsch Is this ticket still valid for you?

Else, i would close it.

Cheers,
Stev

**Comment by thorstenhirsch** [comment]
Let's keep it open for 2 more weeks. I might find the time now to work on it.

**Comment by thorstenhirsch** [comment]
Unfortunately I couldn't reproduce the error. I upgraded my system's CPU in the time since opening this issue, which obviously shouldn't have had any effect on this matter, but it's the only difference I can think of. Well that - and I've upgraded to your latest ISO.

Don't know what to do other than closing this issue. Sorry.

P.S.: The ISO you currently provide doesn't contain the ZFS modules. They probably failed to build due to a nasty change in kernel 6.2.8, see https://github.com/openzfs/zfs/issues/14658

**Comment by stevleibelt** [comment]
@thorstenhirsch no problem, thanks for your response and "cleaning up your trash" (aka closing this issue) :-).

Also thanks for your hint about the iso. I am currently trying to either find an old and working iso to create a new one. See [issue/18](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs/issues/18)

Best regards. Hopefully, zfs is kicking strong asap :-).

**Comment by stevleibelt** [comment]
@thorstenhirsch I was able to find an old iso and uploaded it to the [webpage](https://archzfs.leibelt.de). The build date time is `2023-02-21T16:51:58`.

Cheers,
Stev
