### ISSUE TITLE
Broken due to GPL

### ISSUE THREAD

**Issue by testos77** [stevleibelt/arch-linux-live-cd-iso-with-zfs#18]
With kernel 6.2.8 building of zfs-dkms is broken -> 
https://github.com/openzfs/zfs/issues/14555

e.g. discussion at 
https://aur.archlinux.org/packages/zfs-dkms

https://github.com/openzfs/zfs/issues/14658

Could you provide a last known working (iso) version?

**Comment by stevleibelt** [comment]
@testos77 

I will try to search one in my backups. But right now, there is a small use case for this iso. All you could do is to boot up a system and mount an existing zfs pool to backup data.

I've started a [branch](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs/tree/implement_support_for_more_packages) to support more packages.
What you could do else is to play around with the `--repro-index` option to find a sweet spot to create a iso with an old linux header.

Cheers,
Stev

**Comment by testos77** [comment]
> I will try to search one in my backups. But right now, there is a small use case for this iso. All you could do is to boot up a system and mount an existing zfs pool to backup data.

Thx a lot. 
I guess building 6.2.7 with --repro-index should work. As this kernel change made two machines with zfs encryption unbootable (I didn't recognized the compile error while updating) this iso would help a lot.

**Comment by stevleibelt** [comment]
FTL,  found a webpage called [When root on ZFS breaks on Arch Linux…](https://blog.mnus.de/2023/03/archlinux-zfs/) which is helpful to fix issues.

I am currently updating my machines without updating the kernel.

**Comment by stevleibelt** [comment]
FTL,  found a webpage called [When root on ZFS breaks on Arch Linux…](https://blog.mnus.de/2023/03/archlinux-zfs/) which is helpful to fix issues.

I am currently updating my machines without updating the kernel.

Furthermore, I've opened [issue/213](https://gitlab.archlinux.org/archlinux/archiso/-/issues/213) in the archiso repository asking why mkarchiso does not stop when building a module fails.

**Comment by stevleibelt** [comment]
Hopefully last messages to this ticket @testos77 

I've implemented a quick fix with [this commit](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs/commit/2aa8cbc1cb563364497df228f16c2bd8312631c8).
I am now checking the `build.sh.log` after the `mkarchiso` call and stop the build script if an error in the log was detected.

**Comment by testos77** [comment]
@stevleibelt Hope you had a great journey - thx a lot for all your work. My systems are running again, until - let's see what zfs 2.1.10 will bring
